/**
 * The Python bridge's sample output (bridge/fixtures/sample_messages.jsonl, generated by
 * `python bridge/depth_bridge.py --source synthetic --dump 5 --occupancy 8 6 --voxels 8 6 4 --surface 8 6`)
 * must pass the real zod schema in protocol.ts. This is the contract test
 * between the two implementations: if either side drifts, this fails.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { bridgeFrameToInput, decodeOccupancy, decodeSurface, decodeVoxels, parseBridgeMessage, PROTOCOL_VERSION, surfaceByteToDepth, type BridgeFrame, type BridgeHello } from '../../src/sim/input/protocol';

const fixturePath = fileURLToPath(new URL('../../bridge/fixtures/sample_messages.jsonl', import.meta.url));
const lines = readFileSync(fixturePath, 'utf8').split(/\r?\n/).filter(line => line.trim().length > 0);
const messages = lines.map(line => parseBridgeMessage(line));
const hello = messages[0] as BridgeHello;
const frames = messages.slice(1) as BridgeFrame[];
const inUnit = (v: [number, number, number]) => v.every(c => c >= 0 && c <= 1);
/** Index of the largest byte (first one wins on ties). */
const argmax = (data: Uint8Array) => { let best = -1, index = 0; for (let i = 0; i < data.length; i++) if (data[i] > best) { best = data[i]; index = i; } return index; };

describe('bridge fixture', () => {
  it('has a hello line followed by frames', () => {
    expect(lines.length).toBeGreaterThanOrEqual(2);
    expect(hello.type).toBe('hello');
    expect(hello.version).toBe(PROTOCOL_VERSION);
    expect(hello.source).toBe('synthetic');
    expect(hello.box.z[0]).toBeLessThan(hello.box.z[1]);
    expect(hello.occupancy).toEqual({ width: 8, height: 6 });
    expect(hello.voxels).toEqual({ nx: 8, ny: 6, nz: 4 });
    expect(hello.surface).toEqual({ width: 8, height: 6 });
    expect(frames.length).toBeGreaterThanOrEqual(1);
    for (const f of frames) expect(f.type).toBe('frame');
  });

  it('frames are sequential with a monotonic clock', () => {
    frames.forEach((f, i) => expect(f.seq).toBe(i));
    for (let i = 1; i < frames.length; i++) expect(frames[i].t).toBeGreaterThanOrEqual(frames[i - 1].t);
  });

  it('hands stay inside the unit box with ordered extents', () => {
    let seen = 0;
    for (const f of frames) for (const h of f.hands) {
      seen++;
      expect(inUnit(h.pos)).toBe(true);
      expect(h.conf).toBeGreaterThan(0);
      expect(h.extent).toBeDefined();
      const [lo, hi] = h.extent!;
      expect(inUnit(lo) && inUnit(hi)).toBe(true);
      for (let a = 0; a < 3; a++) { expect(lo[a]).toBeLessThanOrEqual(h.pos[a]); expect(h.pos[a]).toBeLessThanOrEqual(hi[a]); }
      for (const p of h.points ?? []) expect(inUnit(p)).toBe(true);
    }
    expect(seen).toBeGreaterThan(0); // the synthetic script starts with a hand present
  });

  it('occupancy decodes to the size announced in hello, row 0 = top', () => {
    const { width, height } = hello.occupancy!;
    for (const f of frames) {
      expect(f.occupancy).toBeDefined();
      const grid = decodeOccupancy(f.occupancy!, width, height);
      expect(grid.data.length).toBe(width * height);
      // The blob's occupancy must sit around the hand's centroid: the hottest cell row/col agree with pos.
      const hand = f.hands[0];
      if (!hand) continue;
      let best = 0, bestIndex = 0;
      for (let i = 0; i < grid.data.length; i++) if (grid.data[i] > best) { best = grid.data[i]; bestIndex = i; }
      expect(best).toBeGreaterThan(0);
      const row = Math.floor(bestIndex / width), col = bestIndex % width;
      expect(Math.abs((col + .5) / width - hand.pos[0])).toBeLessThan(1.5 / width);
      expect(Math.abs((row + .5) / height - hand.pos[1])).toBeLessThan(1.5 / height);
    }
  });

  it('voxels decode to nx*ny*nz bytes, x fastest, and peak at the hand in the slab of its depth', () => {
    const { nx, ny, nz } = hello.voxels!;
    for (const f of frames) {
      expect(f.voxels).toBeDefined();
      const grid = decodeVoxels(f.voxels!, nx, ny, nz);
      expect(grid.data.length).toBe(nx * ny * nz);
      expect(() => decodeVoxels(f.voxels!, nx, ny, nz + 1)).toThrow();
      const hand = f.hands[0];
      if (!hand) continue;
      const peak = argmax(grid.data);
      expect(grid.data[peak]).toBeGreaterThan(0);
      // Layout: index = (z * ny + y) * nx + x. The hottest voxel is under the centroid...
      const gz = Math.floor(peak / (nx * ny)), gy = Math.floor((peak % (nx * ny)) / nx), gx = peak % nx;
      expect(Math.abs((gx + .5) / nx - hand.pos[0])).toBeLessThan(1.5 / nx);
      expect(Math.abs((gy + .5) / ny - hand.pos[1])).toBeLessThan(1.5 / ny);
      // ...in the slab of the hand's reported depth (its nearest tenth), which the script keeps in the near half of the box.
      expect(Math.abs(gz - Math.floor(hand.pos[2] * nz))).toBeLessThanOrEqual(1);
      expect(gz).toBeLessThan(nz / 2);
      // Summed over z the voxels are the occupancy grid of the same lateral cells, up to per-slab rounding.
      const occ = hello.occupancy!;
      if (occ.width === nx && occ.height === ny) {
        const flat = decodeOccupancy(f.occupancy!, occ.width, occ.height);
        for (let j = 0; j < ny; j++) for (let i = 0; i < nx; i++) {
          let sum = 0;
          for (let k = 0; k < nz; k++) sum += grid.data[(k * ny + j) * nx + i];
          expect(Math.abs(sum - flat.data[j * nx + i])).toBeLessThanOrEqual(nz);
        }
      }
    }
  });

  it('surface decodes to width*height bytes whose nearest scanned cell is the hand at its depth', () => {
    const { width, height } = hello.surface!;
    for (const f of frames) {
      expect(f.surface).toBeDefined();
      const surface = decodeSurface(f.surface!, width, height);
      expect(surface.data.length).toBe(width * height);
      expect(() => decodeSurface(f.surface!, width + 1, height)).toThrow();
      const hand = f.hands[0];
      if (!hand) continue;
      let nearest = 256, nearestIndex = -1, scanned = 0;
      for (let i = 0; i < surface.data.length; i++) {
        const v = surface.data[i];
        if (v === 0) { expect(surfaceByteToDepth(v)).toBeNull(); continue; }
        scanned++;
        if (v < nearest) { nearest = v; nearestIndex = i; }
      }
      expect(scanned).toBeGreaterThan(0);
      // The smallest nonzero byte is the nearest point of the scan: the middle of the synthetic dome, at the hand's depth.
      const row = Math.floor(nearestIndex / width), col = nearestIndex % width;
      expect(Math.abs((col + .5) / width - hand.pos[0])).toBeLessThan(1.5 / width);
      expect(Math.abs((row + .5) / height - hand.pos[1])).toBeLessThan(1.5 / height);
      expect(Math.abs(surfaceByteToDepth(nearest)! - hand.pos[2])).toBeLessThan(.02);
      // Every cell the occupancy grid sees is scanned too (same lateral cells).
      const occ = hello.occupancy!;
      if (occ.width === width && occ.height === height) {
        const flat = decodeOccupancy(f.occupancy!, width, height);
        for (let i = 0; i < flat.data.length; i++) if (flat.data[i] > 0) expect(surface.data[i]).toBeGreaterThan(0);
      }
    }
  });

  it('converts into input frames with every field and stats forwarded', () => {
    for (const f of frames) {
      const input = bridgeFrameToInput(f, 1000, 1010, hello);
      expect(input.source).toBe('depth');
      expect(input.sequence).toBe(f.seq);
      expect(input.occupancy?.width).toBe(8);
      expect(input.voxels).toEqual(decodeVoxels(f.voxels!, 8, 6, 4));
      expect(input.voxels?.data.length).toBe(8 * 6 * 4);
      expect(input.surface).toEqual(decodeSurface(f.surface!, 8, 6));
      expect(input.surface?.data.length).toBe(8 * 6);
      expect(input.hands.length).toBe(f.hands.length);
      expect(typeof input.stats?.pixels).toBe('number');
      expect(typeof input.stats?.processingMs).toBe('number');
    }
    // Without a hello the sizes are unknown and the fields stay undefined rather than guessed.
    const blind = bridgeFrameToInput(frames[0], 1000, 1010, null);
    expect(blind.voxels).toBeUndefined();
    expect(blind.surface).toBeUndefined();
  });
});
