/**
 * The Python bridge's sample output (bridge/fixtures/sample_messages.jsonl,
 * generated by `python bridge/depth_bridge.py --source synthetic --dump 5 --occupancy 8 6`)
 * must pass the real zod schema in protocol.ts. This is the contract test
 * between the two implementations: if either side drifts, this fails.
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { bridgeFrameToInput, decodeOccupancy, parseBridgeMessage, PROTOCOL_VERSION, type BridgeFrame, type BridgeHello } from '../../src/sim/input/protocol';

const fixturePath = fileURLToPath(new URL('../../bridge/fixtures/sample_messages.jsonl', import.meta.url));
const lines = readFileSync(fixturePath, 'utf8').split(/\r?\n/).filter(line => line.trim().length > 0);
const messages = lines.map(line => parseBridgeMessage(line));
const hello = messages[0] as BridgeHello;
const frames = messages.slice(1) as BridgeFrame[];
const inUnit = (v: [number, number, number]) => v.every(c => c >= 0 && c <= 1);

describe('bridge fixture', () => {
  it('has a hello line followed by frames', () => {
    expect(lines.length).toBeGreaterThanOrEqual(2);
    expect(hello.type).toBe('hello');
    expect(hello.version).toBe(PROTOCOL_VERSION);
    expect(hello.source).toBe('synthetic');
    expect(hello.box.z[0]).toBeLessThan(hello.box.z[1]);
    expect(hello.occupancy).toEqual({ width: 8, height: 6 });
    expect(frames.length).toBeGreaterThanOrEqual(1);
    for (const f of frames) expect(f.type).toBe('frame');
  });

  it('frames are sequential with a monotonic clock', () => {
    frames.forEach((f, i) => expect(f.seq).toBe(i));
    for (let i = 1; i < frames.length; i++) expect(frames[i].t).toBeGreaterThanOrEqual(frames[i - 1].t);
  });

  it('hands stay inside the unit box with ordered extents', () => {
    let seen = 0;
    for (const f of frames) for (const h of f.hands) {
      seen++;
      expect(inUnit(h.pos)).toBe(true);
      expect(h.conf).toBeGreaterThan(0);
      expect(h.extent).toBeDefined();
      const [lo, hi] = h.extent!;
      expect(inUnit(lo) && inUnit(hi)).toBe(true);
      for (let a = 0; a < 3; a++) { expect(lo[a]).toBeLessThanOrEqual(h.pos[a]); expect(h.pos[a]).toBeLessThanOrEqual(hi[a]); }
      for (const p of h.points ?? []) expect(inUnit(p)).toBe(true);
    }
    expect(seen).toBeGreaterThan(0); // the synthetic script starts with a hand present
  });

  it('occupancy decodes to the size announced in hello, row 0 = top', () => {
    const { width, height } = hello.occupancy!;
    for (const f of frames) {
      expect(f.occupancy).toBeDefined();
      const grid = decodeOccupancy(f.occupancy!, width, height);
      expect(grid.data.length).toBe(width * height);
      // The blob's occupancy must sit around the hand's centroid: the hottest cell row/col agree with pos.
      const hand = f.hands[0];
      if (!hand) continue;
      let best = 0, bestIndex = 0;
      for (let i = 0; i < grid.data.length; i++) if (grid.data[i] > best) { best = grid.data[i]; bestIndex = i; }
      expect(best).toBeGreaterThan(0);
      const row = Math.floor(bestIndex / width), col = bestIndex % width;
      expect(Math.abs((col + .5) / width - hand.pos[0])).toBeLessThan(1.5 / width);
      expect(Math.abs((row + .5) / height - hand.pos[1])).toBeLessThan(1.5 / height);
    }
  });

  it('converts into input frames with stats forwarded', () => {
    for (const f of frames) {
      const input = bridgeFrameToInput(f, 1000, 1010, hello);
      expect(input.source).toBe('depth');
      expect(input.sequence).toBe(f.seq);
      expect(input.occupancy?.width).toBe(8);
      expect(input.hands.length).toBe(f.hands.length);
      expect(typeof input.stats?.pixels).toBe('number');
      expect(typeof input.stats?.processingMs).toBe('number');
    }
  });
});
